### ISSUE TITLE
Could you provide an example of aliases?

### ISSUE THREAD

**Issue by Herograme** [VirtualButFake/fusion_autocomplete#2]
A simple example of how the configuration works

**Comment by tijnepema** [comment]
The entire extension runs on a bunch of regex expressions; we just use the aliases that were given to check whether a function that is related to Fusion is currently being written.

The "New Aliases" is used to scan for the "New" function inside Fusion (Fusion.New) and will be used to provide classname and property autocomplete. This defaults to "new" and "e", as people will generally call it New/new

The "Fusion Aliases" is used to check whether the function that is currently being written comes from Fusion, and should generally be set to something like "fusion" or "Fusion".

Hope this clarifies it a little! If not, let me know!
